# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: David Dinsmore Designer/Developer
email: dinsmore.david@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  David Dinsmore is a digital designer and front-end developer who believes web applications should be as fast as they are beautiful.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://ddinsmore.com" # the base hostname & protocol for your site
github_username:  dinsmore
include: ["_pages"]
permalink: /:title/
sass:
  style: compressed


# Build settings
markdown: kramdown
